### PR TITLE
Psych fixes

### PR DESCRIPTION
**Pull request by dhsmit6900**
Fixes clearing error and sets permissions in psychController. Sets permissions in mainViewController. Sets tabs to be invisible based on permissions. psychController create notes set to invisible based on permissions. Implements login since it is now needed to run the permissions. Added create button and empty method for psychController - for Robert. Sample login data is in comments at the top of the loginController.

### CODE REVIEW

**Comment by amblas5687** [comment]
@cttimm 

MainFXApp recommendations:
delete the import at line 6
keep the connection con and scene at lines 25-27 and delete the one from psych fixes (21-22).
keep anchor pane setup at lines 35-36, delete the one from line 41,keep the DB con at line 38. 

In mainViewController, keep the stuff from psych fixes (lines 56-60)

**Comment by dhsmit6900** [comment]
We don't need line 25 in mainFXApp though.

**Comment by amblas5687** [comment]
Leo needs it for his controller.

Anna Blasingame
amblas5687@ung.edu<mailto:amblas5687@ung.edu>

On Apr 20, 2017, at 21:46, Danni <notifications@github.com<mailto:notifications@github.com>> wrote:


We don't need line 25 in mainFXApp though.

**Comment by dhsmit6900** [comment]
Creating the scene out there?

Sent from my iPhone

On Apr 20, 2017, at 9:55 PM, Anna Blasingame <notifications@github.com<mailto:notifications@github.com>> wrote:

Leo needs it for his controller.

Anna Blasingame
amblas5687@ung.edu<mailto:amblas5687@ung.edu><mailto:amblas5687@ung.edu>

On Apr 20, 2017, at 21:46, Danni <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


We don't need line 25 in mainFXApp though.

**Comment by amblas5687** [comment]
He needs it because it lets him do a pop up and set the new scene as primary scene. @leomazuran  isn't that right?

**Comment by dhsmit6900** [comment]
What about the getter?

Sent from my iPhone

On Apr 20, 2017, at 9:57 PM, Anna Blasingame <notifications@github.com<mailto:notifications@github.com>> wrote:


He needs it because it lets him do a pop up and set the new scene as primary scene. @leomazuran<https://github.com/leomazuran> isn't that right?

**Comment by amblas5687** [comment]
The getter lets him access the scene.

**Comment by dhsmit6900** [comment]
Why is that a thing?

Sent from my iPhone

On Apr 20, 2017, at 10:00 PM, Anna Blasingame <notifications@github.com<mailto:notifications@github.com>> wrote:


The getter lets him access the scene.

**Comment by amblas5687** [comment]
IDK. We shall wait for his input and explanation.

**Comment by dhsmit6900** [comment]
Travis doesn't like it either.

Sent from my iPhone

On Apr 20, 2017, at 10:01 PM, Anna Blasingame <notifications@github.com<mailto:notifications@github.com>> wrote:


IDK. We shall wait for his input and explanation.

**Comment by amblas5687** [comment]
Ok. Well sorry about that. It doesn't impede how the project functions.

**Comment by dhsmit6900** [comment]
I know. I would just like to know what it's needed for.

Sent from my iPhone

On Apr 20, 2017, at 10:04 PM, Anna Blasingame <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok. Well sorry about that. It doesn't impede how the project functions.

**Comment by amblas5687** [comment]
Leo said it's not his. Hunt continues to find out why. It doesn't inhibit the project currently so I say keep it and merge. If it is redundant, we will remove it. @cttimm @dhsmit6900

**Comment by dhsmit6900** [comment]
Okay. That's fine.

Sent from my iPhone

On Apr 20, 2017, at 10:31 PM, Anna Blasingame <notifications@github.com<mailto:notifications@github.com>> wrote:


Leo said it's not his. Hunt continues to find out why. It doesn't inhibit the project currently so I say keep it and merge. If it is redundant, we will remove it. @cttimm<https://github.com/cttimm> @dhsmit6900<https://github.com/dhsmit6900>

**Comment by cttimm** [comment]
Creating a seperate branch for this merge.

**Pull request closed without merging**
